import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Provider from "../../components/Provider";
import ToasterProvider from "@/providers/ToasterProvider";

import "@/styles/globals.scss";
import { Figtree } from "next/font/google";

const font = Figtree({ subsets: ["latin"] });

export const metadata = {
  title: "Marquet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Provider>
      <html lang="en" className="">
        <body
          className={`${font.className} overflow-x-hidden flex flex-col min-h-screen bg-neutral-50`}
        >
          <ToasterProvider />
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </Provider>
  );
}
