import React from 'react'
import Head from 'next/head'
import CartItems from '@/components/CartItems'
import Divider from '@/components/Divider'
import { useDispatch, useSelector } from 'react-redux'
import Breadcrumbs from '@/components/Breadcrumbs'
import ProductList from '@/components/ProductList'
import { BsBagFill, BsBag } from 'react-icons/bs'

import { SlBag } from 'react-icons/sl'
import LayoutStyles from '../styles/layout/Layout.module.scss'
import BasketStyles from '../styles/pages/Basket.module.scss'

const Basket = () => {
  const quantity = useSelector((state) => state.cart.quantity)
  const cart = useSelector((state) => state.cart)

  return (
    <div className={LayoutStyles.page}>
      <Head>
        <title>Marquet | Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/MarquetLogo.ico" />
      </Head>
      <Breadcrumbs />

      <div className={BasketStyles.basketHeader}>
        <BsBag className={BasketStyles.icon} />
        <h1>My Basket</h1>
      </div>
      {!quantity > 0 ? (
        <div>
          <h1>There are no items in your basket. Start shopping!</h1>
        </div>
      ) : (
        <>
          <ProductList products={cart.products}/>
        </>
      )}

    </div>
  )
}

export default Basket