import React from 'react'
import Head from 'next/head'
import CartItems from '@/components/CartItems'
import Divider from '@/components/Divider'
const Basket = () => {

  return (
    <>
      <Head>
        <title>Marquet | Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/MarquetLogo.ico" />
      </Head>
      <div className="cartPage">
        <CartItems />
      </div>
    </>
  )
}

export default Basket