import React from 'react'
import Head from 'next/head'
import { motion } from "framer-motion";

import FavouriteStyles from '../styles/pages/Favourites.module.scss'
import AltProducts from '@/components/AltProducts'
import Breadcrumbs from '@/components/Breadcrumbs'
import { HiHeart } from 'react-icons/hi'
import Newsletter from '@/components/Newsletter'

import LayoutStyles from '../styles/layout/Layout.module.scss'

const Favourites = () => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    >
      <div className={LayoutStyles.page}>
        <Head>
          <title>Marquet | Favourites</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/MarquetLogo.ico" />
        </Head>
        <Breadcrumbs />
        <div className={FavouriteStyles.favouritesHeader}>
          <HiHeart className={FavouriteStyles.icon} />
          <h1>Saved Items</h1>
        </div>
        <div>
          <AltProducts />
        </div>
        <Newsletter />
      </div>
    </motion.div>
  )
}

export default Favourites