import React, { useEffect } from 'react'
import Head from 'next/head'

import SaleBanner from '@/components/SaleBanner'
import Carousel from '@/components/Carousel'
import Divider from '@/components/Divider'
import Options from '@/components/Options'
import Newsletter from '@/components/Newsletter'
import Misc from '@/components/Misc'
import Featured from '@/components/Featured'
import Slider from '@/components/Slider'
import HomeHeader from '@/components/HomeHeader'

import LayoutStyles from '../styles/layout/Layout.module.scss'

export default function Home() {

  useEffect(() => {
    const countdown = () => {
        const currentDate = new Date().getTime();
        const countDate = new Date('September 15, 2023 00:00:00').getTime();
        
        const diff = countDate - currentDate;
    
        const second = 1000;
        const minute = second * 60;
        const hour = minute * 60;
        const day = hour * 24;
    
        const textDay = Math.floor(diff / day);
        const textHour = Math.floor((diff % day) / hour);
        const textMinute = Math.floor((diff % hour) / minute);
        const textSecond = Math.floor((diff % minute) / second);
    
        const outputHours = (textHour).toLocaleString('en-US', { minimumIntegerDigits: 2, useGrouping: false })
        const outputMinutes = (textMinute).toLocaleString('en-US', { minimumIntegerDigits: 2, useGrouping: false })
        const outputSeconds = (textSecond).toLocaleString('en-US', { minimumIntegerDigits: 2, useGrouping: false })
    
        const timer = document.querySelectorAll('#timer');
        timer.forEach(time => {
            time.innerHTML = outputHours + ':' + outputMinutes + ':' + outputSeconds;
        })
    }
    
    setInterval(countdown, 100);
  }, [])

  return (
    <div className={LayoutStyles.page}>
      <Head>
        <title>Marquet | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/MarquetLogo.ico" />
      </Head>
      
      <HomeHeader 
        header="Sale on Now"
        body="Exclusive top brands at the best prices, only at Marquet"
      />

      <Carousel />
      <SaleBanner />
      <Options />
      <Misc />
      <Divider 
        heading="our top exclusives"
        text="latest additions to marquet"
      />
      <Featured />
      <Slider />
      <Newsletter />
    </div>
  )
}

