import React from 'react'
import axios from 'axios'
import { useRouter } from 'next/router';
import ProductList from '@/components/ProductList'
import Breadcrumbs from '@/components/Breadcrumbs';
import SearchStyles from '../styles/pages/Search.module.scss'
import Newsletter from '@/components/Newsletter';
import Options from '@/components/Options';
import Head from 'next/head';

import LayoutStyles from '../styles/layout/Layout.module.scss'

export default function Search({ productList }) {
  const router = useRouter();
  const paramQuery = Object.values(router.query)[0];

  return (
    <div className={LayoutStyles.page}>
      <Head>
        <title>Marquet | Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/MarquetLogo.ico" />
      </Head>
      <Breadcrumbs />
      <div className={SearchStyles.header}>
        <p>Your search results for:</p>
        <h1>"{paramQuery}"</h1>
        <span>{productList.length} results found</span>
      </div>
      <div>
        {productList ? (
          <ProductList paramQuery={paramQuery} products={productList} />
        ) : (
          <div>
            <p>You have no items saved.</p>
          </div>
        )}
      </div>
      <Options />
      <Newsletter />
    </div>
  )
}

export const getServerSideProps = async (context) => {
  const id = context.query;
  const value = Object.values(id)[0];
  const res = await axios.get(`https://marquet-nextjs.vercel.app/api/search/${value}`);
  return {
    props: {
      productList: res.data,
    }
  }
}